# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(740, 746)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(745, 0))
        MainWindow.setMaximumSize(QtCore.QSize(745, 16777215))
        MainWindow.setStyleSheet("")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 550))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_login_in = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(19)
        sizePolicy.setHeightForWidth(self.tab_login_in.sizePolicy().hasHeightForWidth())
        self.tab_login_in.setSizePolicy(sizePolicy)
        self.tab_login_in.setStyleSheet("")
        self.tab_login_in.setObjectName("tab_login_in")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_login_in)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tab_login = QtWidgets.QTabWidget(self.tab_login_in)
        self.tab_login.setMinimumSize(QtCore.QSize(0, 0))
        self.tab_login.setStyleSheet("")
        self.tab_login.setObjectName("tab_login")
        self.login_user = QtWidgets.QWidget()
        self.login_user.setObjectName("login_user")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.login_user)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.group_user_login = QtWidgets.QGroupBox(self.login_user)
        self.group_user_login.setMinimumSize(QtCore.QSize(250, 120))
        self.group_user_login.setObjectName("group_user_login")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.group_user_login)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line_username = QtWidgets.QLineEdit(self.group_user_login)
        self.line_username.setObjectName("line_username")
        self.verticalLayout_3.addWidget(self.line_username)
        self.line_password = QtWidgets.QLineEdit(self.group_user_login)
        self.line_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_password.setObjectName("line_password")
        self.verticalLayout_3.addWidget(self.line_password)
        self.btn_login_user = QtWidgets.QPushButton(self.group_user_login)
        self.btn_login_user.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_login_user.setObjectName("btn_login_user")
        self.verticalLayout_3.addWidget(self.btn_login_user)
        self.gridLayout_3.addWidget(self.group_user_login, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 2, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.login_user)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_3.addWidget(self.checkBox, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 4, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 3, 1, 1, 1)
        self.tab_login.addTab(self.login_user, "")
        self.login_sid = QtWidgets.QWidget()
        self.login_sid.setObjectName("login_sid")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.login_sid)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox = QtWidgets.QGroupBox(self.login_sid)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radio_euro = QtWidgets.QRadioButton(self.groupBox)
        self.radio_euro.setObjectName("radio_euro")
        self.horizontalLayout_4.addWidget(self.radio_euro)
        self.radio_de = QtWidgets.QRadioButton(self.groupBox)
        self.radio_de.setObjectName("radio_de")
        self.horizontalLayout_4.addWidget(self.radio_de)
        self.radio_fr = QtWidgets.QRadioButton(self.groupBox)
        self.radio_fr.setObjectName("radio_fr")
        self.horizontalLayout_4.addWidget(self.radio_fr)
        self.radio_ru = QtWidgets.QRadioButton(self.groupBox)
        self.radio_ru.setObjectName("radio_ru")
        self.horizontalLayout_4.addWidget(self.radio_ru)
        self.radio_america = QtWidgets.QRadioButton(self.groupBox)
        self.radio_america.setObjectName("radio_america")
        self.horizontalLayout_4.addWidget(self.radio_america)
        self.radio_tr = QtWidgets.QRadioButton(self.groupBox)
        self.radio_tr.setObjectName("radio_tr")
        self.horizontalLayout_4.addWidget(self.radio_tr)
        self.radio_pl = QtWidgets.QRadioButton(self.groupBox)
        self.radio_pl.setObjectName("radio_pl")
        self.horizontalLayout_4.addWidget(self.radio_pl)
        self.radio_es = QtWidgets.QRadioButton(self.groupBox)
        self.radio_es.setObjectName("radio_es")
        self.horizontalLayout_4.addWidget(self.radio_es)
        self.radio_mx = QtWidgets.QRadioButton(self.groupBox)
        self.radio_mx.setObjectName("radio_mx")
        self.horizontalLayout_4.addWidget(self.radio_mx)
        self.radio_usa = QtWidgets.QRadioButton(self.groupBox)
        self.radio_usa.setObjectName("radio_usa")
        self.horizontalLayout_4.addWidget(self.radio_usa)
        self.gridLayout_9.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem5, 4, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem6, 6, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem7, 5, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setContentsMargins(-1, 50, -1, -1)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.group_sid_login = QtWidgets.QGroupBox(self.login_sid)
        self.group_sid_login.setMinimumSize(QtCore.QSize(250, 120))
        self.group_sid_login.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.group_sid_login.setObjectName("group_sid_login")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.group_sid_login)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.combo_server = QtWidgets.QComboBox(self.group_sid_login)
        self.combo_server.setObjectName("combo_server")
        self.gridLayout_2.addWidget(self.combo_server, 0, 0, 1, 1)
        self.btn_login_sid = QtWidgets.QPushButton(self.group_sid_login)
        self.btn_login_sid.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_login_sid.setObjectName("btn_login_sid")
        self.gridLayout_2.addWidget(self.btn_login_sid, 2, 0, 1, 1)
        self.line_sid = QtWidgets.QLineEdit(self.group_sid_login)
        self.line_sid.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_sid.setObjectName("line_sid")
        self.gridLayout_2.addWidget(self.line_sid, 1, 0, 1, 1)
        self.gridLayout_8.addWidget(self.group_sid_login, 0, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem8, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem9, 0, 2, 1, 1)
        self.check_save_server = QtWidgets.QCheckBox(self.login_sid)
        self.check_save_server.setObjectName("check_save_server")
        self.gridLayout_8.addWidget(self.check_save_server, 1, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_8, 2, 0, 1, 1)
        self.tab_login.addTab(self.login_sid, "")
        self.gridLayout_5.addWidget(self.tab_login, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_login_in, "")
        self.tab_auction = QtWidgets.QWidget()
        self.tab_auction.setStyleSheet("")
        self.tab_auction.setObjectName("tab_auction")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_auction)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pb = QtWidgets.QProgressBar(self.tab_auction)
        self.pb.setMaximumSize(QtCore.QSize(16777215, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pb.setFont(font)
        self.pb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pb.setMaximum(60)
        self.pb.setProperty("value", 0)
        self.pb.setAlignment(QtCore.Qt.AlignCenter)
        self.pb.setTextVisible(True)
        self.pb.setInvertedAppearance(False)
        self.pb.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.pb.setFormat("")
        self.pb.setObjectName("pb")
        self.verticalLayout.addWidget(self.pb)
        self.pbm = QtWidgets.QProgressBar(self.tab_auction)
        self.pbm.setEnabled(True)
        self.pbm.setMaximumSize(QtCore.QSize(16777215, 10))
        self.pbm.setMinimum(0)
        self.pbm.setMaximum(60)
        self.pbm.setProperty("value", 0)
        self.pbm.setAlignment(QtCore.Qt.AlignCenter)
        self.pbm.setTextVisible(False)
        self.pbm.setObjectName("pbm")
        self.verticalLayout.addWidget(self.pbm)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.btn_start = QtWidgets.QPushButton(self.tab_auction)
        self.btn_start.setMinimumSize(QtCore.QSize(100, 40))
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout_3.addWidget(self.btn_start)
        self.gridLayout_6.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lb_user_name = QtWidgets.QLabel(self.tab_auction)
        self.lb_user_name.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lb_user_name.setTextFormat(QtCore.Qt.AutoText)
        self.lb_user_name.setObjectName("lb_user_name")
        self.horizontalLayout.addWidget(self.lb_user_name)
        self.lb_user_credits = QtWidgets.QLabel(self.tab_auction)
        self.lb_user_credits.setObjectName("lb_user_credits")
        self.horizontalLayout.addWidget(self.lb_user_credits)
        self.lb_min_credits = QtWidgets.QLabel(self.tab_auction)
        self.lb_min_credits.setObjectName("lb_min_credits")
        self.horizontalLayout.addWidget(self.lb_min_credits)
        self.lb_select_item = QtWidgets.QLabel(self.tab_auction)
        self.lb_select_item.setObjectName("lb_select_item")
        self.horizontalLayout.addWidget(self.lb_select_item)
        self.lb_time_work_bot = QtWidgets.QLabel(self.tab_auction)
        self.lb_time_work_bot.setObjectName("lb_time_work_bot")
        self.horizontalLayout.addWidget(self.lb_time_work_bot)
        self.gridLayout_6.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.table = QtWidgets.QTableWidget(self.tab_auction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table.sizePolicy().hasHeightForWidth())
        self.table.setSizePolicy(sizePolicy)
        self.table.setMinimumSize(QtCore.QSize(0, 0))
        self.table.setSizeIncrement(QtCore.QSize(0, 0))
        self.table.setBaseSize(QtCore.QSize(0, 0))
        self.table.setStyleSheet("")
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.gridLayout_6.addWidget(self.table, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_limit_credit = QtWidgets.QPushButton(self.tab_auction)
        self.btn_limit_credit.setObjectName("btn_limit_credit")
        self.horizontalLayout_2.addWidget(self.btn_limit_credit)
        self.btn_all_max_bet = QtWidgets.QPushButton(self.tab_auction)
        self.btn_all_max_bet.setObjectName("btn_all_max_bet")
        self.horizontalLayout_2.addWidget(self.btn_all_max_bet)
        self.btn_update_win = QtWidgets.QPushButton(self.tab_auction)
        self.btn_update_win.setObjectName("btn_update_win")
        self.horizontalLayout_2.addWidget(self.btn_update_win)
        self.btn_update_bot = QtWidgets.QPushButton(self.tab_auction)
        self.btn_update_bot.setObjectName("btn_update_bot")
        self.horizontalLayout_2.addWidget(self.btn_update_bot)
        self.btn_donate = QtWidgets.QPushButton(self.tab_auction)
        self.btn_donate.setObjectName("btn_donate")
        self.horizontalLayout_2.addWidget(self.btn_donate)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_auction, "")
        self.scrollArea = QtWidgets.QScrollArea(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 720, 168))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(0, 100))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_4.addWidget(self.plainTextEdit, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tab_login.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", ""))
        self.group_user_login.setTitle(_translate("MainWindow", "User and Password"))
        self.line_username.setPlaceholderText(_translate("MainWindow", "username"))
        self.line_password.setPlaceholderText(_translate("MainWindow", "password"))
        self.btn_login_user.setText(_translate("MainWindow", "login"))
        self.checkBox.setText(_translate("MainWindow", "save user and password"))
        self.tab_login.setTabText(self.tab_login.indexOf(self.login_user), _translate("MainWindow", "User"))
        self.groupBox.setTitle(_translate("MainWindow", "Global servers"))
        self.radio_euro.setText(_translate("MainWindow", "Europa"))
        self.radio_de.setText(_translate("MainWindow", "Germany"))
        self.radio_fr.setText(_translate("MainWindow", "France"))
        self.radio_ru.setText(_translate("MainWindow", "Russia"))
        self.radio_america.setText(_translate("MainWindow", "America"))
        self.radio_tr.setText(_translate("MainWindow", "Turkey"))
        self.radio_pl.setText(_translate("MainWindow", "Poland"))
        self.radio_es.setText(_translate("MainWindow", "Spain"))
        self.radio_mx.setText(_translate("MainWindow", "Mexiko"))
        self.radio_usa.setText(_translate("MainWindow", "USA"))
        self.group_sid_login.setTitle(_translate("MainWindow", "Server and Sid"))
        self.btn_login_sid.setText(_translate("MainWindow", "login"))
        self.line_sid.setPlaceholderText(_translate("MainWindow", "sid"))
        self.check_save_server.setText(_translate("MainWindow", "save server"))
        self.tab_login.setTabText(self.tab_login.indexOf(self.login_sid), _translate("MainWindow", "Sid"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_login_in), _translate("MainWindow", "Login in"))
        self.pbm.setFormat(_translate("MainWindow", "0"))
        self.btn_start.setText(_translate("MainWindow", "Start"))
        self.lb_user_name.setText(_translate("MainWindow", "User:"))
        self.lb_user_credits.setText(_translate("MainWindow", "Credit:"))
        self.lb_min_credits.setText(_translate("MainWindow", "Limit credit:"))
        self.lb_select_item.setText(_translate("MainWindow", "Select item:"))
        self.lb_time_work_bot.setText(_translate("MainWindow", "Time:"))
        self.btn_limit_credit.setText(_translate("MainWindow", "Limit credit"))
        self.btn_all_max_bet.setText(_translate("MainWindow", "All max bet"))
        self.btn_update_win.setText(_translate("MainWindow", "Update win"))
        self.btn_update_bot.setText(_translate("MainWindow", "Update bot"))
        self.btn_donate.setText(_translate("MainWindow", "Donate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_auction), _translate("MainWindow", "Auction"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

